-- USER SQL
CREATE USER "C##PROJECTDB" IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##PROJECTDB" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##PROJECTDB" ;
GRANT "RESOURCE" TO "C##PROJECTDB" ;

-- SYSTEM PRIVILEGES